version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:pass@postgres:35432/db
      NODE_ENV: development
      PORT: 3333
    ports:
      - "3333:3333"
    command: npm run dev
    volumes:
      - .:/home/app
      - /home/app/node_modules
      - .env.docker:/home/app/.env
  postgres:
    image: postgres:10.4
    ports:
      - "35432:5432"
    volumes:
      - ./docker/pg/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_DATABASE}"
